import Head from 'next/head';
import Link from 'next/link';
import styles from '../styles/Home.module.css';
import { RiExternalLinkLine } from "react-icons/ri";

export default function About() {

  return (
    <div className={styles.container}>
      <Head>
        <title>Butterfy</title>
        <meta name="description" content="Generated by butterfy" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header>
        <h1>Butterfy</h1>
        <div className="button">
          <Link href="/signin">
            <button>Login</button>
          </Link>
        </div>
      </header>

      <main className={styles.main}>
        <div>
          Butterfy is a collection of insightful content, sourced and curated by the people. Here, you choose in a 4-staged voting process what is really transformational content.
        </div>

        <div className="button">
          <Link href="/">
            <button id="exploring">Start Exploring</button>
          </Link>
        </div>

        <div className="break"><hr/></div>
      </main>

    </div>
  );
}
