import Head from 'next/head'
import Link from 'next/link';
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Butterfy</title>
        <meta name="description" content="Generated by butterfy" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to Butterfy!
        </h1>

        <p>
          <Link href="/signup">Sign up</Link>
          <br />
          <br />
          <Link href="/signin">Sign in</Link>
          <br />
          <br />
          <Link href="/passwordResetForm">Password reset</Link>
          <br />
          <br />
          <Link href="/passwordRecoveryForm">Password recovery</Link>
        </p>
      </main>
    </div>
  );
}
